### ISSUE TITLE
Migrating Component types for HTML elements

### ISSUE THREAD

**Issue by adaptaconer** [Salable/gds#149]
As explained in [this post](https://stackoverflow.com/a/74890103), I think we should transition our element typings away from `HTMLAttributes<T>` to using `ComponentPropsWithoutRef<T>` or `ComponentPropsWithRef<T>`.

This resolves an issue documented in another issue #147. Currently using `HTMLAttributes<T>`, it does not detect the `type` attribute of a button component as a valid prop when it should be. Using the `ComponentPropsWithoutRef<T>` instead resolves this issue.

Happy for thoughts on the issue though.

**Comment by adaptajoe** [comment]
I believe we're now doing this? Can we close @adaptaconer ?

**Comment by adaptaconer** [comment]
This has already been merged and marked on JIRA, must have forgotten to update here. Will close.
