### ISSUE TITLE
Migrate UI-Library Components to using AMOU system

### ISSUE THREAD

**Issue by adaptaconer** [Salable/gds#166]
Once the migration is complete and the GDS is in use in Salable, we should revisit the components migrated and ensure they're using the new AMOU system as optimally as possible. This would also allow us to consolidate the design tokens used in the system. For example, cut down from 15+ similar versions of gray to a more manageable number that has stepped differences.

**Comment by adaptajoe** [comment]
Can we close this now? @rahuladaptavist @adaptaconer

**Comment by adaptaconer** [comment]
I believe this ticket is still required. Some of the components migrated towards the end of the migration don't fully utilize the AMOU system so we could migrate them quicker and not block the salable-mono migration. So, we should go back and check all the components to see if we can refactor them to use the AMOU system more.

Also, I believe we still need a call with Dan to agree on a fixed color palette across both the GDS and Figma so we only use those colors and nothing extra. This would allow us to cut down on the 15 greys, 10 reds, etc to a more manageable number that aligns everywhere.
