### ISSUE TITLE
Excessive spacing on Product Card submenu buttons

### ISSUE THREAD

**Issue by adaptajoe** [Salable/gds#236]
As per the title. To replicate, create a Product, and click the Ellipsis button, and view the `Edit` and `Deprecate` buttons.

<img width="1222" alt="Screenshot 2023-02-16 at 14 44 59" src="https://user-images.githubusercontent.com/110164298/219396882-27e58097-08f9-4078-8b48-b68e0167c03f.png">

**Comment by adaptaconer** [comment]
This is not an issue on production anymore so closing the ticket as not required.

![Screenshot 2023-03-28 at 15 03 32](https://user-images.githubusercontent.com/107639532/228263560-6097446d-5f85-423f-acda-c2274c067413.png)
