### ISSUE TITLE
Pass style prop to Status component

### ISSUE THREAD

**Issue by joshokoro** [Salable/gds#282]
### Issue:
Providing the style on the Status component doesn't have any effect.

### How to reproduce
`<Status style={{ padding: measurements['1'] }} />`
The padding on the Status component remains the same, even though the one provided in the prop should override the current value

**Comment by adaptajoe** [comment]
Thanks for raising this @joshokoro - I'll get a fix out for this.

**Comment by adaptajoe** [comment]
Merged in #285 - Just note @joshokoro that if we have multiple, recurring instances of `Status` with custom styles, please raise a new ticket and we can implement it as a type baked directly into `Status`. 😁
